baseurl:  # the subpath of your site, e.g. /Max
#url: https://basemax.github.io/Max # the base hostname & protocol for your site, e.g. http://example.com

title: "Max Base"
description: "@github developer maintainer. Full-Time Open-Sourcerer. Full-stack programmer. In the path of a real computer engineer... (Compiler enthusiast)"

markdown: kramdown

# Configure the jekyll-category-pages
category_path: "blog"
category_layout: "category_index.html"

strict_front_matter: true

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-avatar
  - jekyll-sitemap
  - jekyll-paginate
  # - jekyll-target-blank
  - jekyll-redirect-from
  - jekyll-category-pages

collections:
  posts:
    output: true
    sidebar_label: Posts
    permalink: /blog/:categories/:title/

  # category:
  #   output: true
  #   permalink: /blog/:title/
