baseurl:  # the subpath of your site, e.g. /Max
#url: https://basemax.github.io/Max # the base hostname & protocol for your site, e.g. http://example.com

title: "Max Base"
description: "@github developer maintainer. Full-Time Open-Sourcerer. Full-stack programmer. In the path of a real computer engineer... (Compiler enthusiast)"

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

collections:
  posts:
    output: true
    sidebar_label: Posts
    permalink: /blog/:categories/:title/
